### ISSUE TITLE
Grouping rectangles to single bin

### ISSUE THREAD

**Issue by tionkje** [soimy/maxrects-packer#20]
I have a set of rectangles that have to be packed into some bins.
But there are some rects that have to be together in the same bin (to prevent multiple textures in a shader)

Is there a way to achieve this using tags?
I noticed currently each tag creates a new bin, and a bin with a tag does not accept any untagged rects.

**Comment by soimy** [comment]
Yes, I think we don't have that feature yet. Currently, rect without tag will have a defaut bin tag, thus tagged rects will not packed into the defaut bins.

**Comment by CosmoMyzrailGorynych** [comment]
It will be epic if it is implemented. My use case is packing animated sprites into atlases, but not spreading any animation over multiple atlases.

I have some heuristics in mind that might help with this job, but I need to check whether an array of rectangles may fit into the current bin prior to actually adding them.

**Comment by soimy** [comment]
Implemented on branch https://github.com/soimy/maxrects-packer/tree/non-exclusive-tag
introducing new packer option `exclusiveTag`, if set to `false`, packer will try to pack sprites with the same tag into the same bin, if all bin cannot fit, new bin is created.

Test needed @CosmoMyzrailGorynych @tionkje

**Comment by CosmoMyzrailGorynych** [comment]
Ok, time to make some tests.
For the record, I ended up with this code that did the job: https://github.com/ct-js/ct-js/blob/ac6f02c103b123e510999add3669c81f205914f7/src/node_requires/exporter/textures.js#L163-L323

**Comment by soimy** [comment]
This feature is merged in the new `2.7.0` version, just update maxrects-packer

**Comment by CosmoMyzrailGorynych** [comment]
Ok, here is the "comparison". Both cases use the same set of sprites. Restrictions:

* Each sprite/animation has a unique tag.
* Each ship has a pair of sprites (With and without a jet flame). Pairs should not be separated.
* All the aliens from https://kenney.nl/assets/platformer-pack-redux (side-view aliens) should be on one atlas. They are in one sprite.
* Small items from https://kenney.nl/assets/platformer-pack-redux (keys, flags) are individual sprites that can be packed arbitrarily.


# First case — 2048x2048 atlases.
It is expected that there will be a lot of backgrounds alone in separate atlases, as they have padding and two of them won't fit.

## My approach: (13 bins)
![2020-09-17_13-38](https://user-images.githubusercontent.com/3174357/93409889-03ec2780-f8ec-11ea-86b4-688f79fcc976.png)

## https://github.com/soimy/maxrects-packer/tree/non-exclusive-tag (12 bins)
![2020-09-17_13-21](https://user-images.githubusercontent.com/3174357/93409931-18c8bb00-f8ec-11ea-8b8e-cca395f78e72.png)

Okay, this case sucks, now:

# Second case — 4kx4k bins

## My approach (2 bins):
![2020-09-17_13-40](https://user-images.githubusercontent.com/3174357/93410022-50376780-f8ec-11ea-8a83-39b5de1ec02b.png)

## https://github.com/soimy/maxrects-packer/tree/non-exclusive-tag (2 bins):
![2020-09-17_13-26](https://user-images.githubusercontent.com/3174357/93410054-62190a80-f8ec-11ea-8c34-dbe65bd3ecd4.png)

# Observations

Both methods seem to work. My method seems to be more space-efficient with sprites relatively smaller than the bin's size.

There is no sorting algorithm across numerous tags in https://github.com/soimy/maxrects-packer/tree/non-exclusive-tag (using 
b4827b8 commit), or there is something wrong with it. See the 4kx4k case. We clearly see that the `a0` atlas (on the left) could contain all the coins, flags, diamons, and keys (they all have different tags), and probably all the aliens, too. It seems that it creates a new bin after the first failure, skipping all the smaller rectangles. I feel that a combination of very wide and very long sprites will make unreasonably large amount of bins (will try to do so soon).

**Comment by CosmoMyzrailGorynych** [comment]
Ok so I set up that "extreme" case with horizontal/vertical sprites:

3 boxes of 2000x64 size and 3 rects of 64x2000 (blue ones).
2 rects of 1800x64 and 2 of 64x1800 (pink ones).
Bins are restricted to be at max 2048x2048 pixels.

A simple solution is putting all the vertical rects in one bin, and the horizontal ones — into another. We can get 2 bins this way.

# The results
They both are awful.

Upper images — v2.7.0, bottom images — my approach. Both produce 4 bins.

![изображение](https://user-images.githubusercontent.com/3174357/93420384-e4acc480-f902-11ea-92ff-394ce5911aba.png)

And here is the packed result **without** tagging at all:
![изображение](https://user-images.githubusercontent.com/3174357/93420595-63096680-f903-11ea-8c3b-914655114cc3.png)

**Comment by soimy** [comment]
Thanks, @CosmoMyzrailGorynych ! Very detailed testing. 
Currently, I do not have time to do any practical case test so yours is really helpful!.

**Comment by soimy** [comment]
I just adopted this new feature into my Repo https://github.com/soimy/atlasify
Everything working as expected so far.

**Comment by CosmoMyzrailGorynych** [comment]
> [`fix: Non-exclusive tag logic: Restart test iteration on next tag group`](https://github.com/soimy/maxrects-packer/commit/8b59925a1d50e17290e12b934a8400015bd094cd#diff-bcb985c18bd60dc3f9d811b0169c413fR184)
![изображение](https://user-images.githubusercontent.com/3174357/93529540-2cc5f880-f990-11ea-9419-1c66224db339.png)

:D

# Testing 8b59925

## "Extreme" case with very long/very tall images: 
![2020-09-18_09-24](https://user-images.githubusercontent.com/3174357/93530441-b3c7a080-f991-11ea-8b22-2a70e48be691.png)

Perfect :ok_hand: 

## Aliens and ships, 2k×2k

![2020-09-18_09-25](https://user-images.githubusercontent.com/3174357/93530543-d6f25000-f991-11ea-9688-912c66d973f7.png)

11 atlases, it is an improvement if compared to the previous 12 atlases from v2.7.0. :+1:

## Aliens and ships, 4k×4k

![2020-09-18_09-36](https://user-images.githubusercontent.com/3174357/93530929-862f2700-f992-11ea-8487-6fa90a5a062d.png)

Does the job in a pretty optimal way :clap:

## Summary
Great work :clap: I feel it is time to ship 8b59925 and close this issue :rocket:

**Comment by soimy** [comment]
Close via eb3c6657ed08eb253b32c6ce54710a0c2d7286f6
New version is now https://github.com/soimy/maxrects-packer/releases/tag/v2.7.1
