### ISSUE TITLE
Border padding ?

### ISSUE THREAD

**Issue by Samsy** [soimy/maxrects-packer#5]
Is there a way to add pad on glyphs that are on the edges ? like a border-padding ? 

( W @ %  etc.. )

![DrukTextWide-Bold-oldold](https://user-images.githubusercontent.com/3786958/57767133-967d2500-7700-11e9-8662-f65bcaa13bf3.png)

**Comment by soimy** [comment]
It is a rare case, better do this in the compositing phase, not packing phase

**Comment by Samsy** [comment]
Can you point me where this thing could happen ? I'd try to get it working if you want it

**Comment by soimy** [comment]
This module is meant to do just position calculation of given rects. compositing procedure is when you read the `x/y/w/h` and put images together with `node-canvas` or `jimp` things.

But on your case, `border` must be taken into account for position calculation for the final atlas description xml/json. Tweaking the algorithm cannot be just a few words.
Don't worry, I'll do it soon. Stay tuned.

**Comment by soimy** [comment]
btw, @Samsy are you making MSDF font generator? Take a look at my repo https://github.com/soimy/msdf-bmfont-xml
Might save you some time.

**Comment by Samsy** [comment]
Yes I'm using this one at first, but I'm trying to bake some drop shadow into glyph, problem is.. it needs space border padding for the letter on the edges :p 

Many thanks again !

**Comment by soimy** [comment]
One trick will be a bigger `distanceRange` >= your shadow shift, with `--vector` svg output. Dropshadow and styling can be done within each glyph rectangle.

**Comment by soimy** [comment]
@Samsy new release `2.4.0-alpha.0` include this fix, can you confirm `border` feature working as you expected?
